{% set name = "lume-astra" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ec3772b06a80b9552143fff6adf1c313cebaba2067e07c1c782441a2d49f1b35

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - distgen
    - numpy
    - openpmd-beamphysics

test:
  imports:
    - astra

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python wrapper for Astra (A Space Charge Tracking Algorithm, DESY) for use in LUME
  description: |
    Tools for analyzing and viewing particle data in the openPMD standard,
    extension beamphysics.

extra:
  recipe-maintainers:
    - ChristopherMayes
